#!/bin/bash

set -e

# get list of packages to install (before the BLACKLIST keyword)
PACKAGES=$(sed -e '/#[ ]*BLACKLIST/,$d' $1 | sed "/^#/d" | uniq | sed -z "s/\n/ /g")

# use rosinstall_generator to create a rosinstall YAML string
rosinstall_generator $PACKAGES --rosdistro melodic --deps --tar > /tmp/rosinstall.dat

# get the list of packages we will need to pull (do not pull existing packages)
cat /tmp/rosinstall.dat | dt_filter_packages --tar --keys-only > /tmp/rosinstall.newkeys.dat

# merge the existing workspace with the one defined in the rosinstall YAML string
wstool merge -t src /tmp/rosinstall.dat

# use wstool to pull the new packages
wstool update -t src $(cat /tmp/rosinstall.newkeys.dat)

# clean up
rm -f /tmp/rosinstall.dat
rm -f /tmp/rosinstall.newkeys.dat

set +e
